[package]
name = "pool-performance"
version = "0.1.0"
authors = ["Alexander Polyakov <aleksandr.polyakov@kupibilet.ru>"]

[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
tokio-threadpool = "0.1"
